version: '3.4'
services:
  react.app:
    image: soo9028/react-nginx-app:v1
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3001
    ports:
      - 3001:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    platform: linux/amd64
